-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 11:52:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema microx_log
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema microx_log
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `microx_log` DEFAULT CHARACTER SET utf8mb4 ;
USE `microx_log` ;

-- -----------------------------------------------------
-- Table `microx_log`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microx_log`.`logs` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `fecha_movimiento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(255) NOT NULL,
  `movimiento` VARCHAR(255) NOT NULL,
  `contenido` VARCHAR(255) NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;