-- MySQL Script generated by MySQL Workbench
-- Sun Feb 11 12:26:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema microx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema microx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `microx` DEFAULT CHARACTER SET utf8mb4 ;
USE `microx` ;

-- -----------------------------------------------------
-- Table `microx`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microx`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `imagen` LONGBLOB NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microx`.`cuas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microx`.`cuas` (
  `id_cua` INT NOT NULL AUTO_INCREMENT,
  `id_usuaio` INT NOT NULL,
  `fecha_modificacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `imagen` LONGBLOB NOT NULL,
  `contenido` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cua`),
  INDEX `id_usuario_idx` (`id_usuaio` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuaio`)
    REFERENCES `microx`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

