# Form implementation generated from reading ui file '.\src\view\login\Ui_Avatar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Avatar(object):
    def setupUi(self, Avatar):
        Avatar.setObjectName("Avatar")
        Avatar.resize(350, 400)
        Avatar.setMaximumSize(QtCore.QSize(350, 400))
        self.centralwidget = QtWidgets.QWidget(parent=Avatar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("font: 700 24pt \"Inter\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_avatars_defecto = QtWidgets.QFrame(parent=self.frame)
        self.frame_avatars_defecto.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_avatars_defecto.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_avatars_defecto.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_avatars_defecto.setObjectName("frame_avatars_defecto")
        self.verticalLayout_2.addWidget(self.frame_avatars_defecto)
        self.frame_avatar = QtWidgets.QFrame(parent=self.frame)
        self.frame_avatar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_avatar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_avatar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_avatar.setObjectName("frame_avatar")
        self.verticalLayout_2.addWidget(self.frame_avatar)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_subir_imagen = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_subir_imagen.setStyleSheet("font: 10pt \"Inter\";")
        self.btn_subir_imagen.setObjectName("btn_subir_imagen")
        self.horizontalLayout_2.addWidget(self.btn_subir_imagen, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.btn_quitarimagen = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_quitarimagen.setStyleSheet("font: 10pt \"Inter\";")
        self.btn_quitarimagen.setObjectName("btn_quitarimagen")
        self.horizontalLayout_2.addWidget(self.btn_quitarimagen, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btn_guardar = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_guardar.setStyleSheet("font: 10pt \"Inter\";")
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_2.addWidget(self.btn_guardar, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        Avatar.setCentralWidget(self.centralwidget)

        self.retranslateUi(Avatar)
        QtCore.QMetaObject.connectSlotsByName(Avatar)

    def retranslateUi(self, Avatar):
        _translate = QtCore.QCoreApplication.translate
        Avatar.setWindowTitle(_translate("Avatar", "MainWindow"))
        self.label.setText(_translate("Avatar", "Escoge tu avatar"))
        self.btn_subir_imagen.setText(_translate("Avatar", "Subir imagen"))
        self.btn_quitarimagen.setText(_translate("Avatar", "Quitar imagen"))
        self.btn_guardar.setText(_translate("Avatar", "Guardar"))
