# Form implementation generated from reading ui file '.\src\view\login\Ui_Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(350, 350)
        Login.setMinimumSize(QtCore.QSize(350, 350))
        Login.setMaximumSize(QtCore.QSize(350, 350))
        Login.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("font: 700 24pt \"Inter\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setStyleSheet("font: 12pt \"Inter\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.field_usuario = QtWidgets.QLineEdit(parent=self.frame_4)
        self.field_usuario.setStyleSheet("font: 10pt \"Inter\";")
        self.field_usuario.setObjectName("field_usuario")
        self.verticalLayout_3.addWidget(self.field_usuario)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setStyleSheet("font: 12pt \"Inter\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.field_contrasena = QtWidgets.QLineEdit(parent=self.frame_4)
        self.field_contrasena.setStyleSheet("font: 10pt \"Inter\";")
        self.field_contrasena.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.field_contrasena.setObjectName("field_contrasena")
        self.verticalLayout_3.addWidget(self.field_contrasena)
        self.label_estado = QtWidgets.QLabel(parent=self.frame_4)
        self.label_estado.setObjectName("label_estado")
        self.verticalLayout_3.addWidget(self.label_estado, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_registrate = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_registrate.setObjectName("btn_registrate")
        self.horizontalLayout_2.addWidget(self.btn_registrate)
        self.btn_login = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_login.setStyleSheet("")
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_2.addWidget(self.btn_login)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "Usuario"))
        self.label_3.setText(_translate("Login", "Contraseña"))
        self.label_estado.setText(_translate("Login", "Estado"))
        self.btn_registrate.setText(_translate("Login", "Registrate"))
        self.btn_login.setText(_translate("Login", "Login"))
