# Form implementation generated from reading ui file '.\src\view\vMisPub\Ui_VMisPub.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VMisPub(object):
    def setupUi(self, VMisPub):
        VMisPub.setObjectName("VMisPub")
        VMisPub.resize(400, 500)
        VMisPub.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(parent=VMisPub)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("font: 700 20pt \"Inter\";\n"
"border-bottom: 1px solid black;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_publicaciones = QtWidgets.QFrame(parent=self.frame)
        self.frame_publicaciones.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_publicaciones.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_publicaciones.setObjectName("frame_publicaciones")
        self.verticalLayout_2.addWidget(self.frame_publicaciones)
        self.btn_regresar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_regresar.setStyleSheet("font: 10pt \"Inter\";")
        self.btn_regresar.setObjectName("btn_regresar")
        self.verticalLayout_2.addWidget(self.btn_regresar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout.addWidget(self.frame)
        VMisPub.setCentralWidget(self.centralwidget)

        self.retranslateUi(VMisPub)
        QtCore.QMetaObject.connectSlotsByName(VMisPub)

    def retranslateUi(self, VMisPub):
        _translate = QtCore.QCoreApplication.translate
        VMisPub.setWindowTitle(_translate("VMisPub", "MainWindow"))
        self.label.setText(_translate("VMisPub", "VMisPub"))
        self.btn_regresar.setText(_translate("VMisPub", "Regresar"))
